
ccflags-y += -Idrivers/misc/mediatek/nutlet_linuxdriver/armtz/libopensslrsa
ccflags-y += -I../kernel-3.18/include/linux
ccflags-y += -I../kernel-3.18/include/uapi/linux
ccflags-y += -I../kernel-3.18/arch/powerpc/boot
ccflags-y += -I../kernel-3.18/fs/ntfs/

obj-y +=	bn_add.o bn_div.o bn_exp.o bn_lib.o bn_ctx.o bn_mul.o bn_mod.o \
	bn_print.o  buf_str.o bn_rand.o bn_shift.o bn_word.o \
	bn_kron.o bn_sqrt.o bn_gcd.o bn_prime.o bn_sqr.o bn_asm.o \
	bn_recp.o bn_mont.o \
	err.o  mem.o \
	rsa_lib.o rsa_gen_prime.o 
