/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6755. Copyright MediaTek Inc. (C) 2013.
 * Mon Oct 31 15:01:15 2016
 * Do Not Modify the File.
 */

#define CUST_EINT_MD_LEVEL_SENSITIVE        0
#define CUST_EINT_MD_EDGE_SENSITIVE         1


#define PAD_CAM_CLK1		1
#define PAD_DPI_D6		2
#define PAD_DPI_D7		1
#define PAD_INT_SIM1		1
#define PAD_INT_SIM2		2
#define PAD_PWM_A		2


#define CUST_EINT_POLARITY_LOW              0
#define CUST_EINT_POLARITY_HIGH             1
#define CUST_EINT_EDGE_SENSITIVE            0
#define CUST_EINT_LEVEL_SENSITIVE           1




#define CUST_EINT_MD1_0_NAME             "MD1_SIM1_HOT_PLUG_EINT"
#define CUST_EINT_MD1_0_NUM              0
#define CUST_EINT_MD1_0_DEBOUNCE_CN      0
#define CUST_EINT_MD1_0_POLARITY         CUST_EINT_POLARITY_LOW
#define CUST_EINT_MD1_0_SENSITIVE        CUST_EINT_MD_LEVEL_SENSITIVE
#define CUST_EINT_MD1_0_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_DISABLE
#define CUST_EINT_MD1_0_DEDICATED_EN     0
#define CUST_EINT_MD1_0_SRCPIN           PAD_INT_SIM1

#define CUST_EINT_MD1_CNT      1


