#
# Copyright (C) STMicroelectronics 2014. All rights reserved.
#
# This code is STMicroelectronics proprietary and confidential.
# Any use of the code for whatever purpose is subject to
# specific written permission of STMicroelectronics SA.
#



obj-y += core/
obj-y += armtz/
obj-$(CONFIG_MMC_MTK) +=rpmb/

ccflags-y += -I./include -I./ -I./armtz -I./core
#ccflags-y += -I/home/wangl/source/self_alps/alps/kernel-3.10/arch/arm/include/ -I./ -I./armtz -I./core

ccflags-y +=  -Wno-unused-parameter -Wno-unused-function